config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root_path = 'pages#index'
  root to: root_path

  scope ':locale', locale: /#{I18n.available_locales.join('|')}/, defaults: { locale: I18n.locale } do
    root to: root_path

    devise_for :users, controllers: { registrations: 'users/registrations' }
    devise_scope :user do
      get 'users/sign_up/*token', to: 'users/registrations#new'
    end
    resources :organizations
    resources :contacts, except: %i[index show]
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
# frozen_string_literal: true

class Contact < ApplicationRecord
  belongs_to :organization
  belongs_to :contact_type

  validates :contact_type, :data, :organization, presence: true
  validates :data, contact_data: true
end

app/models/contact_type.rb
# frozen_string_literal: true

class ContactType < ApplicationRecord
  CONTACT_TYPES = %w[phone email url messenger].freeze

  has_many :contacts, dependent: :destroy

  validates :main_type, :subtype, presence: true
  validates :main_type, inclusion: { in: CONTACT_TYPES }
  validates :main_type, uniqueness: { scope: :subtype }
end

app/models/invitation.rb
# frozen_string_literal: true

class Invitation < ApplicationRecord
  validates :token, uniqueness: true

  before_create :set_token

  private

  def set_token
    self.token = loop do
      random_token = SecureRandom.urlsafe_base64(nil, false)
      break random_token unless Invitation.exists?(token: random_token)
    end
  end
end

app/models/organization.rb
# frozen_string_literal: true

class Organization < ApplicationRecord
  belongs_to :user
  has_many :contacts, dependent: :destroy

  validates :name, :description, :user, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  has_many :organizations, dependent: :destroy
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :set_locale

  private

  def default_url_options
    { locale: I18n.locale }.merge(super)
  end

  def set_locale
    I18n.locale = extract_locale
  end

  def extract_locale
    parsed_locale = params[:locale]
    return parsed_locale if I18n.available_locales.map(&:to_s).include?(parsed_locale)

    extract_locale_from_header || I18n.locale
  end

  def extract_locale_from_header
    request.env['HTTP_ACCEPT_LANGUAGE']&.scan(/[a-z]{2}/)&.map(&:to_sym)&.find do |locale|
      I18n.available_locales.include?(locale)
    end
  end
end

app/controllers/contacts_controller.rb
# frozen_string_literal: true

class ContactsController < ApplicationController
  before_action :set_contact, only: %i[edit update destroy]

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      redirect_to @contact.organization
    else
      render :new
    end
  end

  def edit; end

  def update
    if @contact.update(contact_params)
      redirect_to @contact.organization
    else
      render :edit
    end
  end

  def destroy
    @contact.destroy
    redirect_to @contact.organization
  end

  private

  def set_contact
    @contact = Contact.find(params[:id])
  end

  def contact_params
    params.require(:contact).permit(:data, :organization_id, :contact_type_id)
  end
end

app/controllers/organizations_controller.rb
# frozen_string_literal: true

class OrganizationsController < ApplicationController
  before_action :set_organization, only: %i[edit show update destroy]

  def index
    @organizations = Organization.all.includes(:user)
  end

  def new
    @organization = Organization.new
  end

  def create
    @organization = Organization.new(organization_params.merge(user: current_user))

    if @organization.save
      redirect_to @organization
    else
      render :new
    end
  end

  def show
    @contacts = @organization.contacts.includes(:contact_type)
  end

  def edit; end

  def update
    if @organization.update(organization_params)
      redirect_to @organization
    else
      render :edit
    end
  end

  def destroy
    @organization.destroy
    redirect_to organizations_path
  end

  private

  def organization_params
    params.require(:organization).permit(:name, :description)
  end

  def set_organization
    @organization = Organization.find(params[:id])
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def index; end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

module Users
  class RegistrationsController < Devise::RegistrationsController
    skip_before_action :set_minimum_password_length, only: %i[new create]
    before_action :configure_permitted_parameters
    before_action :check_token_presence, only: %i[new create]

    after_action :destroy_invitation, only: %i[create]

    private

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:token])
    end

    def check_token_presence
      redirect_to new_user_session_path, alert: t('controllers.messages.link_not_unique') unless valid_token?
    end

    def valid_token?
      Invitation.find_by(token: params[:token])
    end

    def destroy_invitation
      return unless user_signed_in?

      Invitation.find_by(token: params[:token]).destroy
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/devise_shared_helper.rb
# frozen_string_literal: true

module DeviseSharedHelper
  def devise_registerable?
    devise_mapping.registerable? && controller_name != 'registrations'
  end

  def devise_recoverable?
    devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  end

  def devise_confirmable?
    devise_mapping.confirmable? && controller_name != 'confirmations'
  end

  def devise_lockable?
    devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  end

  def omniauth_link(provider)
    link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider)
  end
end

app/helpers/pages_helper.rb
# frozen_string_literal: true

module PagesHelper
end

app/views/common/_errors.html.haml
- if resource.errors.any?
  #error_explanation
    %h2
      = t('organizations.prohibited', count: resource.errors.count)
    %ul
      - resource.errors.full_messages.each do |message|
        %li= message

app/views/contacts/_form.html.haml
%h1
  = I18n.t('contacts.form.title')
  \:
.ui.placeholder.segment
  %h2.ui.header.center.aligned= t('contacts.form.title')
  .ui.one.column.very.relaxed.stackable.grid
    .column
      = form_for contact, html: { class: 'ui form' } do |f|
        = render 'common/errors', resource: contact
        .field
          = f.label :data
          .ui.left.icon.input.email
            = f.text_field :data
        .field
          = f.label :organization
          = select 'contact',
                   'organization_id',
                   Organization.all.collect { |p| [p.name, p.id] },
                   include_blank: true
        .field
          = f.label :contact_type
          .ui.left.icon.input
            = f.collection_select :contact_type_id, ContactType.all, :id, :main_type
        %div{ style: 'display: flex; justify-content: center' }
          = f.submit t('crud.actions.contact.new'), class: 'ui blue submit button', style: 'margin: 0'
          = button_to t('crud.actions.back'), organizations_path, class: 'ui blue submit button', style: 'margin: 0'

app/views/contacts/edit.html.haml
= render 'form', contact: @contact

app/views/contacts/new.html.haml
= render 'form', contact: @contact

app/views/layouts/_menu.html.haml
.ui.secondary.menu
  %h4.ui.header.item
    = link_to 'Thank You', root_path, class: 'main-link'
  .right.menu
    - if current_user.present?
      %h5.item= current_user.email
      = button_to t('sign_out'), destroy_user_session_path, method: :delete, class: 'ui inverted blue button'
    - else
      = button_to t('sign_in'), new_user_session_path, method: :get, class: 'ui inverted blue button'

app/views/layouts/_notices_alerts.html.haml
- if notice
  .ui.success.small.message
    %i.close.icon
    .header
      = notice
- if alert
  .ui.negative.small.message
    %i.close.icon
    .header
      = alert

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ content: 'text/html; charset=UTF-8', 'http-equiv' => 'Content-Type' }/
    %title Thankyou
    = csrf_meta_tags
    = csp_meta_tag
    = javascript_pack_tag 'thankYou/index'
    = stylesheet_pack_tag 'thankYou/assets/stylesheets/app'
  %body.ui.container.relaxed
    %header
      = render 'layouts/menu'
    = render 'layouts/notices_alerts'
    #root
    .ui.container
      = yield

app/views/organizations/_form.html.haml
%h1
  = I18n.t('organizations.form.title')
  \:
= form_for organization do |f|
  = render 'common/errors', resource: organization
  .container
    = f.label :name
    %br/
    = f.text_field :name
  .container
    = f.label :description
    %br/
    = f.text_field :description
    %br/
  = f.submit t('crud.actions.create')
= link_to I18n.t('crud.actions.back'), organizations_path

app/views/organizations/edit.html.haml
= render 'form', organization: @organization

app/views/organizations/index.html.haml
- @organizations.each do |organization|
  %ul
    %li
      = organization.user.email
      %br/
      = link_to organization.name, organization
      %br/
      = organization.description
= link_to t('crud.actions.new'), new_organization_path

app/views/organizations/new.html.haml
= render 'form', organization: @organization

app/views/organizations/show.html.haml
= @organization.user.email
%br/
= @organization.name
%br/
= @organization.description
%br/
%div{ style: 'display: flex' }
  = link_to t('crud.actions.back'), organizations_path, class: 'ui white submit button'
  = link_to t('crud.actions.update'), edit_organization_path(@organization), class: 'ui orange submit button'
  = button_to t('crud.actions.destroy'),
              organization_path(@organization),
              method: :delete, class: 'ui red submit button', style: 'display: inline, margin: 0'
%p= t('contacts.show.title')
.ui.list
  - @contacts.each do |contact|
    .item
      = contact.contact_type.main_type
      \- #{contact.contact_type.subtype}
      %br/
      = contact.data
      %br/
      %div{ style: 'display: flex; justify-content: left' }
        = link_to t('crud.actions.update'), edit_contact_path(contact), class: 'ui orange submit button'
        = button_to t('crud.actions.destroy'),
                    contact_path(contact),
                    method: :delete, class: "delete_contact_#{contact.id} ui red submit button"
= link_to t('crud.actions.new'), new_contact_path, class: 'ui blue submit button'

app/views/pages/index.html.haml
#thank-you

app/views/pages/root.html.erb
<div id='thank-you'></div>